### ISSUE TITLE
Wiki2023 passage length

### ISSUE THREAD

**Issue by LiinXemmon** [fate-ubw/RAGLAB#5]
RAGLAB is awesome, and I truly appreciate your work. However, I noticed that the Wiki2023 passages are not chunked, and some of them are too long. The ColBERT indexing sets the maximum length to 300, which seems inconsistent. Is this an intentional setting or a bug?

Additionally, how can I reuse the embeddings you've uploaded to Hugging Face? I always receive a prompt to input 'yes' and then rebuild the index.

**Comment by fate-ubw** [comment]
First of all, thank you very much for pointing out this problem, and secondly, I apologize for responding to your question so late. In response to your question, I carefully checked the settings for using Colbert for wiki2023, and in short, the problem you said does exist.
1. Wiki2023 passages are indeed not chunked, which makes the length of each passage in wiki2023 very long
2. The ColBERT indexing sets the maximum length to 300, which does not align with the length of wiki2023 text passages. In the early experiments, we tried to use wiki2023 for experiments, but found that the results were not good, so we replaced wiki2018 as knowledge base.
Thanks again for the issue, I'll be reworking wiki2023 and then rebuilding colbert embedding for wiki2023 in the next few days 
Q： how can I reuse the embeddings you've uploaded to Hugging Face? 
A: Because colbert enforces the use of absolute paths, and the processed index file` metadata.json` also enforces the binding of absolute paths, which makes reusing wiki2018 embedding a bit problematic, although I wrote a description of modifying absolute paths in the readme, I know that this is still difficult for others to reproduce
To put it simply, you need to complete these 3 steps

Step1: First of all, you need to complete the first step, download the data inside wiki2018 and wiki2018 embedding, here you need to note that when you download data from https://huggingface.co/datasets/RAGLAB/data/tree/main.
 Please do not ask to change the default path, please be sure to store according to this path
 embedding： /data/retrieval/colbertv2.0_embedding/wiki2018/
 passages：  /data/retrieval/colbertv2.0_passages/wiki2018/
 
Step2: After you have downloaded Wiki2018 Passages and Wiki2018 Embedding, please modify the path metadata.json in the Embedding Index.
  ~~~
  cd RAGLAB
  vim /data/retrieval/colbertv2.0_embedding/wiki2018/indexes/wiki2018/metadata.json
  # change root path, other parameters do not need to be modified
  "collection": "/{your_root_path}/RAGLAB/data/retrieval/colbertv2.0_passages/wiki2018/wiki2018.tsv",
  "experiment": "/{your_root_path}/RAGLAB/data/retrieval/colbertv2.0_embedding/wiki2018"
  ~~~

Step3: Please modify the paths of 'index_dbPath' and 'text_dbPath' in the yaml file
  ～～～
  cd RAGLAB/config/colbert_server
  vim colbert_server.yaml
  index_dbPath: {your_root_path}/RAGLAB/data/retrieval/colbertv2.0_embedding/wiki2018
  text_dbPath: {your_root_path}/RAGLAB/data/retrieval/colbertv2.0_passages/wiki2018/wiki2018.tsv
  ～～～
If you still receive a prompt to input 'yes' and then rebuild the index, it must be that there is an error in your path settings, please follow the readme to double-check the path settings, this problem is indeed prone to problems. Thank you very much for raising this issue and pointing out the problem with wiki2023, I will update the repository in the near future to solve this problem, welcome to continue to ask qeustion~

**Comment by LiinXemmon** [comment]
Thank you for your detailed response! I will try it then.

**Comment by fate-ubw** [comment]
Feel free to reopen this issue~
